forget.cgi:main.c ../lib/URIDecode.* ../lib/operateDb.* ../lib/status.h
	gcc -W -g main.c ../lib/URIDecode.* ../lib/operateDb.* ../lib/status.h -o forget.cgi -I/usr/include/mysql -L/usr/lib64/mysql -lmysqlclient
